# FULLY GENERATED BY AI BUT STILL WORKS BUT ITS COOL SO ITS CHILL
import re
import requests
from urllib.parse import urlparse, urljoin, parse_qs, unquote
from pathlib import Path
from bs4 import BeautifulSoup

# ── Supported sites ──────────────────────────────────────────────────────────
SUPPORTED_SITES = {
    "truffled.lol":  "https://truffled.lol",
    "azgames.io":    "https://azgames.io",
}

# Fallback base (kept for any direct calls that don't go through run())
_DEFAULT_BASE = "https://truffled.lol"

EJS_TAG = "4.0.9"
EJS_RAW = f"https://raw.githubusercontent.com/EmulatorJS/EmulatorJS/{EJS_TAG}/data"
EJS_CDN_CORES = f"https://cdn.emulatorjs.org/{EJS_TAG}/data/"
SENTINEL_FILE = ".ejs_downloaded"
OPTIONAL_ROOT_ASSETS = {
    "/apple-touch-icon.png",
    "/favicon.ico",
    "/logo192.png",
    "/logo512.png",
    "/manifest.json",
    "/site.webmanifest",
}

PPSPP_CORE_ASSETS = [
    "ppsspp-wasm.data",
    "ppsspp-thread-wasm.data",
    "ppsspp-legacy-wasm.data",
    "ppsspp-assets.zip",
]

# nipplejs.js is excluded here — it needs special post-processing (see download_ejs_sources)
EJS_SOURCE_FILES = [
    "emulator.js",
    "emulator.css",
    "shaders.js",
    "storage.js",
    "gamepad.js",
    "GameManager.js",
    "socket.io.min.js",
    "compression.js",
    "compression/libunrar.js",
    "compression/libunrar.wasm",
    "compression/extract7z.js",
    "localization/en.json",
]

# Appended to nipplejs.js after download.
NIPPLEJS_RESCUE = """
;(function () {
  if (typeof window.nipplejs === 'undefined') {
    if (typeof module !== 'undefined' && module && module.exports) {
      window.nipplejs = module.exports;
    } else if (typeof exports !== 'undefined' && exports && exports.nipplejs) {
      window.nipplejs = exports.nipplejs;
    }
  }
})();
"""

# ── Ruffle self-hosted CDN (latest stable) ──────────────────────────────────
RUFFLE_CDN = "https://unpkg.com/@ruffle-rs/ruffle"


# ── Site detection ───────────────────────────────────────────────────────────

def get_site_base(url: str) -> str:
    """Return the canonical base URL for the site the given URL belongs to."""
    parsed = urlparse(url)
    netloc = parsed.netloc.lower().lstrip("www.")
    for key, base in SUPPORTED_SITES.items():
        if netloc == key or netloc.endswith("." + key):
            return base
    # Unknown site — use the scheme+host from the URL itself so the script
    # can still attempt a best-effort generic download.
    return f"{parsed.scheme}://{parsed.netloc}"


# ── azgames.io helpers ───────────────────────────────────────────────────────

def _scrape_azgames(page_url: str, base: str) -> str:
    """
    azgames.io embeds games in a few different ways:
      1. An <iframe> whose src is the direct game URL (most common).
      2. A data attribute or JS variable pointing at the game bundle.
    We try them in order and fall back to the generic iframe scraper.
    """
    resp = requests.get(page_url, timeout=10)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    # Strategy 1 – <iframe>
    iframe = soup.find("iframe")
    if iframe and iframe.get("src"):
        src = iframe["src"]
        if src.startswith("//"):
            src = "https:" + src
        if not src.startswith("http"):
            src = urljoin(base, src)
        return src

    # Strategy 2 – <div data-game-url="..."> or similar data attributes
    for tag in soup.find_all(True):
        for attr in ("data-game-url", "data-src", "data-url"):
            val = tag.get(attr)
            if val and ("game" in val.lower() or val.endswith((".html", ".htm"))):
                if not val.startswith("http"):
                    val = urljoin(base, val)
                return val

    # Strategy 3 – JS variable assignment like gameUrl = "..."
    for script in soup.find_all("script"):
        text = script.string or ""
        m = re.search(r'(?:gameUrl|game_url|embedUrl|embed_url)\s*[=:]\s*["\']([^"\']+)["\']', text, re.I)
        if m:
            val = m.group(1)
            if not val.startswith("http"):
                val = urljoin(base, val)
            return val

    raise ValueError(f"Could not find a game embed on: {page_url}")


# ── Generic helpers (previously hard-coded to truffled.lol) ─────────────────

def extract_game_url(page_url: str, base: str) -> str:
    parsed = urlparse(page_url)
    qs = parse_qs(parsed.query)
    if "url" in qs:
        inner = unquote(qs["url"][0])
        inner_qs = parse_qs(urlparse(inner).query)
        if "url" in inner_qs:
            inner = unquote(inner_qs["url"][0])
        return base + inner
    return page_url if page_url.startswith("http") else base + page_url


def scrape_game_url_from_page(page_url: str, base: str) -> str:
    resp = requests.get(page_url, timeout=10)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")
    iframe = soup.find("iframe")
    if not iframe or not iframe.get("src"):
        raise ValueError("Could not find an iframe on the page.")
    return extract_game_url(urljoin(base, iframe["src"]), base)


def resolve_game_url(user_url: str, base: str) -> str:
    parsed = urlparse(user_url)
    netloc = parsed.netloc.lower().lstrip("www.")

    # azgames.io — always scrape the listing page
    if "azgames.io" in netloc:
        return _scrape_azgames(user_url, base)

    # truffled.lol (and unknown sites) — original logic
    if "iframe.html" in parsed.path or "mobile.html" in parsed.path:
        return extract_game_url(user_url, base)
    if parsed.path.startswith("/gamefile/") or re.match(r"^/games/", parsed.path):
        return extract_game_url(user_url, base)
    return scrape_game_url_from_page(user_url, base)


def parse_ejs_config(html: str) -> dict:
    config = {}
    for m in re.finditer(r'EJS_(\w+)\s*=\s*["\']([^"\']+)["\']', html):
        config[m.group(1)] = m.group(2)
    return config


def is_old_style_loader(loader_text: str) -> bool:
    return "createElement" in loader_text and "import(" not in loader_text


def ejs_already_downloaded(data_dir: Path) -> bool:
    if (data_dir / SENTINEL_FILE).exists():
        return True
    if (data_dir / "emulator.js").exists():
        return True
    return False


def download_ejs_sources(data_dir: Path, force: bool = False):
    if not force and ejs_already_downloaded(data_dir):
        print(f"  [~] EmulatorJS already present in {data_dir}, skipping.")
        return

    print(f"[*] Downloading EmulatorJS {EJS_TAG} source files from GitHub ...")
    data_dir.mkdir(parents=True, exist_ok=True)

    failed = []
    for rel_path in EJS_SOURCE_FILES:
        dest = data_dir / rel_path
        if dest.exists() and not force:
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        try:
            resp = requests.get(f"{EJS_RAW}/{rel_path}", timeout=30)
            resp.raise_for_status()
            dest.write_bytes(resp.content)
            print(f"  [+] {rel_path}")
        except Exception as e:
            print(f"  [!] Failed: {rel_path} — {e}")
            failed.append(rel_path)

    nipple_dest = data_dir / "nipplejs.js"
    if not nipple_dest.exists() or force:
        try:
            resp = requests.get(f"{EJS_RAW}/nipplejs.js", timeout=30)
            resp.raise_for_status()
            patched_content = resp.content.decode("utf-8", errors="ignore") + NIPPLEJS_RESCUE
            nipple_dest.write_text(patched_content, encoding="utf-8")
            print("  [+] nipplejs.js (patched: window.nipplejs rescue appended)")
        except Exception as e:
            print(f"  [!] Failed: nipplejs.js — {e}")
            failed.append("nipplejs.js")

    en_json = data_dir / "localization" / "en.json"
    en_us_json = data_dir / "localization" / "en-US.json"
    if en_json.exists() and (not en_us_json.exists() or force):
        en_us_json.write_bytes(en_json.read_bytes())
        print("  [+] localization/en-US.json (copied from en.json)")

    emulator_js = data_dir / "emulator.js"
    min_js = data_dir / "emulator.min.js"
    min_css = data_dir / "emulator.min.css"

    if emulator_js.exists() and (not min_js.exists() or force):
        min_js.write_bytes(emulator_js.read_bytes())
        print("  [+] emulator.min.js (copied from emulator.js)")

    if not min_css.exists() or force:
        min_css.write_text("@import url('emulator.css');\n", encoding="utf-8")
        print("  [+] emulator.min.css (shim)")

    if not failed:
        (data_dir / SENTINEL_FILE).write_text(EJS_TAG, encoding="utf-8")
        print(f"  [✓] EmulatorJS source files ready in {data_dir}")
    else:
        print(f"  [!] Completed with {len(failed)} failure(s): {failed}")

    patch_emulatorjs_canvas_resize(data_dir)


def patch_emulatorjs_canvas_resize(data_dir: Path):
    """Backfill a safe resize path for EmulatorJS builds that lack setCanvasSize."""
    replacement = """        const dpr = window.devicePixelRatio || 1;
        const width = positionInfo.width * dpr;
        const height = (positionInfo.height * dpr);
        if (typeof this.Module.setCanvasSize === "function") {
            this.Module.setCanvasSize(width, height);
        } else if (this.Module.canvas) {
            this.Module.canvas.width = width;
            this.Module.canvas.height = height;
        }
        if (!this.handleSettingsResize) return;"""

    for rel_path in ["emulator.js", "emulator.min.js"]:
        target = data_dir / rel_path
        if not target.exists():
            continue
        try:
            text = target.read_text(encoding="utf-8", errors="ignore")
            old = """        const dpr = window.devicePixelRatio || 1;
        const width = positionInfo.width * dpr;
        const height = (positionInfo.height * dpr);
        this.Module.setCanvasSize(width, height);
        if (!this.handleSettingsResize) return;"""
            if old in text:
                patched = text.replace(old, replacement)
                if patched != text:
                    target.write_text(patched, encoding="utf-8")
                    print(f"  [~] Patched resize compatibility in {target.relative_to(data_dir)}")
        except Exception:
            pass


def resolve_rom_url(ejs_game_url: str, base_game_url: str, base: str) -> str:
    if ejs_game_url.startswith("http"):
        return ejs_game_url
    if ejs_game_url.startswith("/"):
        return base + ejs_game_url
    return urljoin(base_game_url, ejs_game_url)


def download_rom(rom_url: str, out_dir: Path) -> Path | None:
    rom_filename = rom_url.split("?")[0].rsplit("/", 1)[-1]
    rom_path = out_dir / rom_filename
    if rom_path.exists():
        print(f"  [~] ROM already exists: {rom_path.name}")
        return rom_path

    print(f"[*] Downloading ROM: {rom_url}")
    try:
        with requests.get(rom_url, timeout=300, stream=True) as resp:
            resp.raise_for_status()
            total = int(resp.headers.get("content-length", 0))
            downloaded = 0
            with open(rom_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=65536):
                    f.write(chunk)
                    downloaded += len(chunk)
                    if total:
                        pct = downloaded * 100 // total
                        mb = downloaded / (1024 * 1024)
                        print(f"\r  [~] {pct:3d}%  {mb:.1f} / {total / (1024*1024):.1f} MB", end="", flush=True)
        print()
        print(f"  [+] ROM saved: {rom_path.name}")
        return rom_path
    except Exception as e:
        print(f"  [!] Failed to download ROM: {e}")
        return None


def patch_index_emulatorjs(index_path: Path, rom_filename: str, ejs_config: dict):
    html = index_path.read_text(encoding="utf-8", errors="ignore")
    core = (ejs_config.get("core") or "").lower()

    html = re.sub(
        r'(EJS_gameUrl\s*=\s*)["\'][^"\']*["\']',
        f'\\1"{rom_filename}"',
        html,
    )

    if "pathtodata" in ejs_config:
        html = re.sub(r'(EJS_pathtodata\s*=\s*)["\'][^"\']*["\']', r'\1"data/"', html)
    else:
        html = html.replace(
            '<script src="loader.js"',
            '<script>var EJS_pathtodata = "data/";</script>\n<script src="loader.js"',
        )

    html = re.sub(r'(EJS_threads\s*=\s*)true\b', r'\1false', html, flags=re.IGNORECASE)

    cores_cdn = EJS_CDN_CORES
    ejs_paths_script = f"""<script>
window.EJS_paths = window.EJS_paths || {{}};
var _c = "{cores_cdn}";
["ppsspp","ppsspp-thread","ppsspp-legacy",
 "nestopia","fceumm","snes9x","snes9x2010",
 "gambatte","mgba","vba_next",
 "genesis_plus_gx","picodrive",
 "mupen64plus_next","mupen64plus_next-thread","mupen64plus_next-legacy",
 "pcsx_rearmed","mednafen_pce","mednafen_pce_fast",
 "mesen","vice_x64","fbalpha2012_cps1"].forEach(function(c) {{
    window.EJS_paths["cores/"+c+"-wasm.data"] = _c+"cores/"+c+"-wasm.data";
    window.EJS_paths["cores/"+c+"-thread-wasm.data"] = _c+"cores/"+c+"-thread-wasm.data";
    window.EJS_paths["cores/"+c+"-legacy-wasm.data"] = _c+"cores/"+c+"-legacy-wasm.data";
}});
window.EJS_paths["cores/ppsspp-assets.zip"] = _c+"cores/ppsspp-assets.zip";
if ({str(core in {"psp", "ppsspp"}).lower()}) {{
    window.EJS_paths["cores/ppsspp-wasm.data"] = "data/cores/ppsspp-wasm.data";
    window.EJS_paths["cores/ppsspp-thread-wasm.data"] = "data/cores/ppsspp-thread-wasm.data";
    window.EJS_paths["cores/ppsspp-legacy-wasm.data"] = "data/cores/ppsspp-legacy-wasm.data";
    window.EJS_paths["cores/ppsspp-assets.zip"] = "data/cores/ppsspp-assets.zip";
}}
</script>
<script>window.EJS_threads = false;</script>
<script src="data/nipplejs.js"></script>
<script src="data/socket.io.min.js"></script>
<script src="data/storage.js"></script>
<script src="data/shaders.js"></script>
<script src="data/gamepad.js"></script>
<script src="data/GameManager.js"></script>
"""

    html = html.replace('<script src="loader.js"', ejs_paths_script + '<script src="loader.js"')
    index_path.write_text(html, encoding="utf-8")
    print(f"  [~] Patched index.html:")
    print(f"       EJS_pathtodata  → data/")
    print(f"       EJS_gameUrl     → {rom_filename}")
    print(f"       EJS_paths       → CDN ({cores_cdn})")
    print(f"       nipplejs        → synchronous <script> before loader.js")


def patch_index_ruffle(index_path: Path, swf_filename: str):
    """
    Rewrite the index.html for a Ruffle/Flash game so it loads from the
    self-hosted CDN instead of the missing /js/main.js reference, and
    points Ruffle at the locally-saved SWF.
    """
    html = index_path.read_text(encoding="utf-8", errors="ignore")

    html = re.sub(r'<script[^>]+src=["\'][^"\']*\/js\/main\.js["\'][^>]*>\s*<\/script>', '', html)
    html = re.sub(r'<script[^>]+src=["\'][^"\']*ruffle[^"\']*["\'][^>]*>\s*<\/script>', '', html, flags=re.IGNORECASE)
    html = re.sub(r'<script[^>]*>.*?RufflePlayer.*?</script>', '', html, flags=re.DOTALL | re.IGNORECASE)

    ruffle_snippet = f"""<script src="ruffle.js"></script>
<script>
  window.addEventListener("load", function () {{
    var player = window.RufflePlayer.newest().createPlayer();
    player.style.width  = "100%";
    player.style.height = "100vh";
    document.body.appendChild(player);
    player.load("{swf_filename}");
  }});
</script>"""

    if "</body>" in html:
        html = html.replace("</body>", ruffle_snippet + "\n</body>")
    else:
        html += "\n" + ruffle_snippet

    index_path.write_text(html, encoding="utf-8")
    print(f"  [~] Patched index.html (Ruffle):")
    print(f"       SWF             → {swf_filename}")
    print(f"       Ruffle loader   → ruffle.js (self-hosted)")
    print(f"       /js/main.js     → removed (site-only, not needed)")


def get_game_name(game_index_url: str) -> str:
    try:
        resp = requests.get(game_index_url, timeout=10)
        soup = BeautifulSoup(resp.text, "html.parser")
        title = soup.find("title")
        if title and title.text.strip():
            name = re.sub(r'[\\/*?:"<>|]', "", title.text.strip())
            return name.strip().lower().replace(" ", "_")
    except Exception:
        pass
    parts = [p for p in urlparse(game_index_url).path.split("/") if p]
    for part in reversed(parts):
        if part != "index.html":
            return part.lower()
    return "unknown_game"


# ── Asset-discovery helpers ──────────────────────────────────────────────────

_ASSET_EXTS = r"wasm|data|ogg|mp3|wav|png|jpg|jpeg|gif|svg|ttf|woff2?|json|lua|lovejs|love|swf|iso|map"


def _is_allowed_origin(url: str, allowed_origins: list[str]) -> bool:
    """Return True if url's origin matches any of the allowed_origins prefixes."""
    return any(url.startswith(o) for o in allowed_origins)


def collect_assets_from_text(text: str, base_url: str, base_game_url: str, url_to_local_path, allowed_origins: list[str]) -> list:
    assets = []

    for match in re.findall(r'url\(["\']?([^"\')\s]+)["\']?\)', text):
        if not match.startswith(("http", "data:", "#")):
            full = urljoin(base_url, match.split("?")[0])
            if _is_allowed_origin(full, allowed_origins):
                assets.append((full, url_to_local_path(full)))

    for match in re.findall(
        rf'["\`\'][\w./\-]+\.(?:{_ASSET_EXTS})["\`\']',
        text,
        flags=re.IGNORECASE,
    ):
        clean = match.strip("\"'`").split("?")[0]
        if not clean.startswith(("http", "data:", "#")):
            full = urljoin(base_url, clean)
            if _is_allowed_origin(full, allowed_origins):
                assets.append((full, url_to_local_path(full)))

    for match in re.findall(r'["\']([^"\']*game\.[a-z0-9]+)["\']', text, flags=re.IGNORECASE):
        clean = match.split("?")[0]
        if not clean.startswith(("http", "data:", "#")):
            full = urljoin(base_url, clean)
            if _is_allowed_origin(full, allowed_origins):
                assets.append((full, url_to_local_path(full)))

    return assets


def asset_url_candidates(url: str) -> list[str]:
    """Return alternate URLs worth trying when the first fetch returns 404."""
    clean_url = url.split("#", 1)[0].split("?", 1)[0]
    parsed = urlparse(clean_url)
    path = parsed.path

    candidates = [clean_url]

    if "/static/js/" in path:
        candidates.append(clean_url.replace("/static/js/", "/", 1))
    if "/static/css/" in path:
        candidates.append(clean_url.replace("/static/css/", "/", 1))

    deduped = []
    seen = set()
    for candidate in candidates:
        if candidate not in seen:
            seen.add(candidate)
            deduped.append(candidate)
    return deduped


def is_optional_asset(url: str) -> bool:
    return urlparse(url).path in OPTIONAL_ROOT_ASSETS


def strip_redirects_from_html(html: str, game_origin: str) -> tuple[str, int]:
    """
    Remove JS and meta-refresh redirects that would send the browser back to
    the live site when the page is opened locally.  Returns (patched_html, count).
    """
    count = 0

    # <meta http-equiv="refresh" content="...">
    before = html
    html = re.sub(r'<meta[^>]+http-equiv=["\']refresh["\'][^>]*>', '', html, flags=re.IGNORECASE)
    if html != before:
        count += html.count("refresh") + 1  # rough

    # window.location / document.location assignments pointing off-origin
    def _kill_location(m):
        nonlocal count
        target = m.group(1)
        parsed = urlparse(target)
        if parsed.scheme in ("http", "https") and not target.startswith(game_origin):
            count += 1
            return f"/* luv.py: redirect removed */ void(0); //{m.group(0)}"
        return m.group(0)

    html = re.sub(
        r'(?:window|document|top|self|parent)\.location(?:\.href)?\s*=\s*["\']([^"\']+)["\']',
        _kill_location,
        html,
    )

    # location.replace("...") / location.assign("...")
    def _kill_location_fn(m):
        nonlocal count
        target = m.group(2)
        parsed = urlparse(target)
        if parsed.scheme in ("http", "https") and not target.startswith(game_origin):
            count += 1
            return f"/* luv.py: redirect removed */ void(0); //{m.group(0)}"
        return m.group(0)

    html = re.sub(
        r'(?:window\.)?location\.(replace|assign)\(["\']([^"\']+)["\']\)',
        _kill_location_fn,
        html,
    )

    return html, count


def rewrite_local_asset_refs_in_text(text: str, out_path: Path, base_game_path: str) -> str:
    """Rewrite root-absolute local asset refs to relative paths when possible."""

    def replace_attr(match):
        url = match.group("url")
        clean = url.split("#", 1)[0].split("?", 1)[0]
        if clean.startswith(base_game_path):
            local_path = out_path / clean[len(base_game_path):]
        else:
            local_path = out_path / clean.lstrip("/")
        if clean.startswith("/") and local_path.exists():
            rel_path = local_path.relative_to(out_path).as_posix()
            return f'{match.group("prefix")}{rel_path}{match.group("suffix")}'
        return match.group(0)

    def replace_css_url(match):
        url = match.group("url")
        clean = url.split("#", 1)[0].split("?", 1)[0]
        if clean.startswith(base_game_path):
            local_path = out_path / clean[len(base_game_path):]
        else:
            local_path = out_path / clean.lstrip("/")
        if clean.startswith("/") and local_path.exists():
            quote = match.group("quote") or ""
            rel_path = local_path.relative_to(out_path).as_posix()
            return f'url({quote}{rel_path}{quote})'
        return match.group(0)

    text = re.sub(
        r'(?P<prefix>\b(?:src|href)=["\'])(?P<url>/[^"\']+)(?P<suffix>["\'])',
        replace_attr,
        text,
    )
    text = re.sub(
        r'url\((?P<quote>["\']?)(?P<url>/[^)"\']+)(?P=quote)\)',
        replace_css_url,
        text,
    )
    return text


def rewrite_local_asset_refs_in_tree(out_path: Path, base_game_path: str):
    updated = 0
    for file_path in out_path.rglob("*"):
        if file_path.suffix.lower() not in {".html", ".htm", ".css"}:
            continue
        try:
            text = file_path.read_text(encoding="utf-8", errors="ignore")
            rewritten = rewrite_local_asset_refs_in_text(text, out_path, base_game_path)
            if rewritten != text:
                file_path.write_text(rewritten, encoding="utf-8")
                updated += 1
        except Exception:
            pass
    if updated:
        print(f"  [~] Rewrote {updated} HTML/CSS file(s) to use local asset paths")


def ensure_placeholder_manifest(index_html: str, out_path: Path, game_name: str):
    """Create a local manifest.json when the page references one but none exists."""
    if "manifest.json" not in index_html.lower():
        return

    manifest_path = out_path / "manifest.json"
    if manifest_path.exists():
        return

    manifest = {
        "name": game_name.replace("_", " ").title(),
        "short_name": game_name[:12],
        "start_url": ".",
        "display": "standalone",
        "background_color": "#000000",
        "theme_color": "#000000",
    }

    import json
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print("  [+] manifest.json (generated placeholder)")


def download_ejs_core_assets(core: str, data_dir: Path):
    """Mirror core-specific EmulatorJS assets locally when we know the core."""
    core = (core or "").lower()
    if core not in {"psp", "ppsspp"}:
        return

    core_dir = data_dir / "cores"
    core_dir.mkdir(parents=True, exist_ok=True)

    for rel_path in PPSPP_CORE_ASSETS:
        dest = core_dir / rel_path
        if dest.exists():
            continue
        url = f"{EJS_CDN_CORES}cores/{rel_path}"
        try:
            resp = requests.get(url, timeout=60)
            resp.raise_for_status()
            dest.write_bytes(resp.content)
            print(f"  [+] cores/{rel_path}")
        except Exception as e:
            print(f"  [!] Failed: cores/{rel_path} — {e}")


def find_swf_in_html(html: str, base_game_url: str) -> str | None:
    soup = BeautifulSoup(html, "html.parser")

    param = soup.find("param", attrs={"name": re.compile(r"movie", re.I)})
    if param and param.get("value"):
        return urljoin(base_game_url, param["value"])

    m = re.search(r'["\']([^"\']*\.swf)["\']', html, re.IGNORECASE)
    if m:
        return urljoin(base_game_url, m.group(1).split("?")[0])

    m = re.search(r'\.load\(["\']([^"\']+\.swf)["\']', html, re.IGNORECASE)
    if m:
        return urljoin(base_game_url, m.group(1).split("?")[0])

    tag = soup.find(src=re.compile(r"\.swf", re.I))
    if tag:
        return urljoin(base_game_url, tag["src"].split("?")[0])

    return None


def is_ruffle_game(html: str, soup: BeautifulSoup) -> bool:
    """Return True when the page uses Ruffle (Flash emulator)."""
    if soup.find("script", src=re.compile(r"ruffle", re.I)):
        return True
    if re.search(r"RufflePlayer|ruffle\.js", html, re.I):
        return True
    if soup.find(attrs={"type": re.compile(r"application/x-shockwave-flash", re.I)}):
        return True
    return False


# ── Main download orchestration ──────────────────────────────────────────────

def download_game(game_index_url: str, out_base: str = "./exported", site_base: str = _DEFAULT_BASE):
    print(f"[*] Resolved game URL: {game_index_url}")
    print(f"[*] Site base: {site_base}")
    game_name = get_game_name(game_index_url)
    print(f"[*] Game name: {game_name}")

    base_game_url = game_index_url.rsplit("/", 1)[0] + "/"

    # The game may be hosted on a different origin than the referring site
    # (e.g. azgames.io listing → gamea.azgame.io game host).  Build a list of
    # all origins we're allowed to pull assets from.
    _parsed_game = urlparse(game_index_url)
    game_origin = f"{_parsed_game.scheme}://{_parsed_game.netloc}"
    allowed_origins: list[str] = list({site_base, game_origin})  # deduplicate
    print(f"[*] Allowed asset origins: {allowed_origins}")

    out_path = Path(out_base) / game_name
    out_path.mkdir(parents=True, exist_ok=True)

    visited = set()
    base_game_path = urlparse(base_game_url).path

    def url_to_local_path(url: str) -> Path:
        clean_url = url.split("?", 1)[0].split("#", 1)[0]
        clean_path = urlparse(clean_url).path
        if clean_path.startswith(base_game_path):
            rel = clean_path[len(base_game_path):]
        else:
            rel = clean_path.lstrip("/")
        return out_path / rel

    def fetch_and_save(url: str, save_path: Path | None = None, silent_404: bool = False, preserve_path: bool = False):
        last_error = None
        for candidate_url in asset_url_candidates(url):
            if candidate_url in visited:
                continue
            visited.add(candidate_url)
            target_path = save_path if preserve_path and save_path is not None else url_to_local_path(candidate_url)
            try:
                resp = requests.get(candidate_url, timeout=60)
                resp.raise_for_status()
            except requests.HTTPError as e:
                last_error = e
                continue
            except Exception as e:
                last_error = e
                continue
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_bytes(resp.content)
            display_url = candidate_url.replace(site_base, "")
            print(f"  [+] {display_url} -> {target_path.relative_to(out_path)}")
            return resp
        if last_error and not silent_404 and not is_optional_asset(url):
            print(f"  [!] Failed to fetch {url}: {last_error}")
        return None

    # ── Download index.html ──────────────────────────────────────────────────
    index_resp = fetch_and_save(game_index_url, out_path / "index.html", preserve_path=True)
    if not index_resp:
        raise RuntimeError("Failed to download game index.html")

    html_text = index_resp.text

    # Strip JS/meta redirects that would bounce the browser back to the live site
    html_text, n_stripped = strip_redirects_from_html(html_text, game_origin)
    if n_stripped:
        (out_path / "index.html").write_text(html_text, encoding="utf-8")
        print(f"  [~] Stripped {n_stripped} redirect(s) from index.html")

    soup = BeautifulSoup(html_text, "html.parser")
    ensure_placeholder_manifest(html_text, out_path, game_name)

    # ── EmulatorJS branch ────────────────────────────────────────────────────
    ejs_config = parse_ejs_config(html_text)
    is_emulatorjs = bool(ejs_config.get("gameUrl") or ejs_config.get("core"))

    if is_emulatorjs:
        core = ejs_config.get("core", "unknown")
        print(f"[*] Detected EmulatorJS game (core: {core})")

        loader_url = urljoin(base_game_url, "loader.js")
        loader_resp = fetch_and_save(loader_url, out_path / "loader.js", preserve_path=True)
        loader_text = loader_resp.content.decode("utf-8", errors="ignore") if loader_resp else ""

        data_dir = out_path / "data"

        if is_old_style_loader(loader_text):
            print(f"[*] Loader style: classic script (4.0.9)")
            download_ejs_sources(data_dir)
        else:
            print(f"[*] Loader style: ES module (new) — CDN zip needed")
            print(f"  [!] Download emulator.min.zip manually:")
            print(f"      https://cdn.emulatorjs.org/stable/data/emulator.min.zip")
            print(f"      Extract to: {data_dir}")

        download_ejs_core_assets(core, data_dir)

        rom_url_raw = ejs_config.get("gameUrl", "")
        if rom_url_raw:
            rom_url = resolve_rom_url(rom_url_raw, base_game_url, site_base)
            rom_path = download_rom(rom_url, out_path)
            if rom_path:
                patch_index_emulatorjs(out_path / "index.html", rom_path.name, ejs_config)
        else:
            print("  [!] EJS_gameUrl not found — set it manually in index.html")

        rewrite_local_asset_refs_in_tree(out_path, base_game_path)

        print(f"\n[✓] {out_path.resolve()}")
        if core == "ppsspp":
            print(f"    Note: PPSSPP core streams from CDN on first launch (~60 MB)")
        return

    # ── Ruffle / Flash branch ────────────────────────────────────────────────
    if is_ruffle_game(html_text, soup):
        print("[*] Detected Ruffle (Flash) game")

        swf_url = find_swf_in_html(html_text, base_game_url)

        if not swf_url:
            for candidate in ["swf.swf", "game.swf", "flash.swf", "index.swf"]:
                test_url = base_game_url + candidate
                try:
                    r = requests.head(test_url, timeout=10)
                    if r.status_code == 200:
                        swf_url = test_url
                        print(f"  [~] SWF found via HEAD probe: {candidate}")
                        break
                except Exception:
                    pass

        if swf_url:
            swf_filename = swf_url.split("?")[0].rsplit("/", 1)[-1]
            swf_path = out_path / swf_filename
            print(f"[*] Downloading SWF: {swf_url.replace(site_base, '')}")
            resp = fetch_and_save(swf_url, swf_path, preserve_path=True)
            if not resp:
                print("  [!] SWF download failed — game may not work offline")
        else:
            swf_filename = "game.swf"
            print(f"  [!] Could not auto-detect SWF URL; set it manually in index.html")

        ruffle_dest = out_path / "ruffle.js"
        if not ruffle_dest.exists():
            print(f"[*] Downloading Ruffle from {RUFFLE_CDN} ...")
            try:
                r = requests.get(RUFFLE_CDN, timeout=30)
                r.raise_for_status()
                ruffle_dest.write_bytes(r.content)
                print("  [+] ruffle.js")
            except Exception as e:
                print(f"  [~] Ruffle CDN fetch skipped ({e}); will use page's ruffle.js")

        patch_index_ruffle(out_path / "index.html", swf_filename)

        _download_generic_assets(
            soup, html_text, base_game_url, out_path, url_to_local_path, fetch_and_save, allowed_origins
        )

        rewrite_local_asset_refs_in_tree(out_path, base_game_path)

        print(f"\n[✓] {out_path.resolve()}")
        return

    # ── Generic HTML5 game branch ────────────────────────────────────────────
    print("[*] Detected generic HTML5 game")
    _download_generic_assets(
        soup, html_text, base_game_url, out_path, url_to_local_path, fetch_and_save, allowed_origins
    )

    rewrite_local_asset_refs_in_tree(out_path, base_game_path)

    for fname in ["game.data", "game.wasm", "game.swf"]:
        explicit_path = out_path / fname
        if not explicit_path.exists():
            print(f"[*] Explicitly trying {fname}...")
            fetch_and_save(base_game_url + fname, explicit_path, silent_404=True, preserve_path=True)

    rewrite_local_asset_refs_in_tree(out_path, base_game_path)

    print(f"\n[✓] {out_path.resolve()}")


def _download_generic_assets(soup, html_text, base_game_url, out_path, url_to_local_path, fetch_and_save, allowed_origins: list[str]):
    """Download all linked assets found in a page's HTML and recurse into JS/CSS."""
    assets = []

    for tag in soup.find_all(["script", "link", "img", "source", "audio", "video"]):
        for attr in ["src", "href", "data-src"]:
            val = tag.get(attr)
            if val and not val.startswith(("http", "//", "data:", "#", "javascript:")):
                full = urljoin(base_game_url, val.split("?")[0])
                if _is_allowed_origin(full, allowed_origins):
                    assets.append((full, url_to_local_path(full)))
            elif val and val.startswith("//"):
                full = "https:" + val.split("?")[0]
                if _is_allowed_origin(full, allowed_origins):
                    assets.append((full, url_to_local_path(full)))
            elif val and val.startswith("http"):
                full = val.split("?")[0]
                if _is_allowed_origin(full, allowed_origins):
                    assets.append((full, url_to_local_path(full)))

    assets += collect_assets_from_text(html_text, base_game_url, base_game_url, url_to_local_path, allowed_origins)
    print(f"[*] Found {len(assets)} initial assets...")

    for url, path in assets:
        resp = fetch_and_save(url, path)
        if not resp:
            continue
        if url.split("?")[0].rsplit(".", 1)[-1].lower() in ("css", "js"):
            try:
                text = resp.content.decode("utf-8", errors="ignore")
                for n_url, n_path in collect_assets_from_text(
                    text, url.rsplit("/", 1)[0] + "/", base_game_url, url_to_local_path, allowed_origins
                ):
                    fetch_and_save(n_url, n_path)
            except Exception:
                pass

    for js_file in out_path.rglob("*.js"):
        try:
            text = js_file.read_text(encoding="utf-8", errors="ignore")
            patched = re.sub(r'(\.(data|wasm|ogg|mp3|wav|png|jpg|json|love|css|swf))\?[^"\'&\s]+', r'\1', text)
            if patched != text:
                js_file.write_text(patched, encoding="utf-8")
                print(f"  [~] Patched cache busters in {js_file.relative_to(out_path)}")
        except Exception:
            pass


def run(url: str, out_base: str = "./exported"):
    site_base = get_site_base(url)
    netloc = urlparse(url).netloc.lower().lstrip("www.")

    known = any(netloc == k or netloc.endswith("." + k) for k in SUPPORTED_SITES)
    if not known:
        print(f"[!] Warning: '{netloc}' is not a recognised site. Attempting best-effort download.")

    game_url = resolve_game_url(url, site_base)
    download_game(game_url, out_base=out_base, site_base=site_base)